[package]
name = "smol"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.30", features = ["derive"] }
humansize = { version = "2.1.3", features = ["impl_style"] }
jwalk = "0.8.1"
shellexpand = "3.1.0"
